import adapter from '@sveltejs/adapter-auto';
import { vitePreprocess } from '@sveltejs/kit/vite';
import { mdsvex } from 'mdsvex';
import codeTitle from 'remark-code-titles';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://kit.svelte.dev/docs/integrations#preprocessors
	// for more information about preprocessors
	preprocess: [mdsvex({ extensions: ['.md'], remarkPlugins: [codeTitle] }), vitePreprocess()],
	extensions: ['.svelte', '.md'],
	// silence warnings about a11y missing child roles in mdsvex as they are generated by ToC. Note this is the error generated by svelte, even though the warning displayed is 'A11y: <a> element should have child content
	onwarn: (warning, defaultHandler) => {
		if (warning.code === 'a11y-missing-content') return;
		defaultHandler(warning);
	},
	kit: {
		// adapter-auto only supports some environments, see https://kit.svelte.dev/docs/adapter-auto for a list.
		// If your environment is not supported or you settled on a specific environment, switch out the adapter.
		// See https://kit.svelte.dev/docs/adapters for more information about adapters.
		adapter: adapter()
	}
};

export default config;
