name: Assign Issue to Repository Owner and Create Project Card
on:
  issues:
    types:
      - opened
      - reopened
permissions:
  issues: write
  repository-projects: write

jobs:
  assignToRepoOwner:
    runs-on: ubuntu-latest

    steps:
      - name: Check if issue creator is the repository owner
        id: check_author
        run: echo "::set-output name=is_owner::${{ github.repository_owner == github.event.issue.user.login }}"

      - name: Assign issue to repository owner
        if: steps.check_author.outputs.is_owner == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ env.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees" \
            -d '{
              "assignees": ["${{ github.repository_owner }}"]
            }'
            
      - name: Create project card
        if: steps.check_author.outputs.is_owner == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ env.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/projects/columns/f75ad846/cards" \
            -d '{
              "note": "Add payload for delete Project column"
            }'
