name: Assign Issue and Create Project Card
on:
  issues:
    types:
      - opened
      - reopened

jobs:
  assignAndCreateCard:
    runs-on: ubuntu-latest

    steps:
      - name: Check if issue creator is the repository owner
        id: check_author
        run: echo "::set-output name=is_owner::${{ github.repository_owner == github.event.issue.user.login }}"


 

      - name: Create project card
        if: steps.check_author.outputs.is_owner == 'true'
        uses: peter-evans/create-or-update-project-card@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        with:
          column_id: f75ad846
          content_id: ${{ github.event.issue.node_id }}
          content_type: Issue
          mediaType: '{"previews":["inertia"]}'
          token: ${{ env.GITHUB_TOKEN }}
