name: Assign issues and create cards
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      repository-projects: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const actor = context.actor;

            github.issues.updateAssignees({
                issue_number: issueNumber,
                owner: owner,
                repo: repo,
                assignees: [actor]
            });

            const projectName = "svelte learning blog";
            const cardTitle = context.issue.title;

            github.projects.createCard({
                project_name: projectName,
                card_title: cardTitle,
                issue_number: issueNumber
            });
