name: Assign Issue and Create Project Card
on:
  issues:
    types:
      - opened
      - reopened

jobs:
  assignAndCreateCard:
    runs-on: ubuntu-latest

    steps:
      - name: Check if issue creator is the repository owner
        id: check_author
        run: echo "::set-output name=is_owner::${{ github.repository_owner == github.event.issue.user.login }}"

 
      - name: Set up environment variables
        run: echo "ACTION_TOKEN=${{ secrets.ACTION_TOKEN }}" >> $GITHUB_ENV

      - name: Assign issue to repository owner
        if: steps.check_author.outputs.is_owner == 'true'
        uses: octokit/request-action@v2.x       
        with:
          route: POST /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees
          headers: |
            Authorization: token ${{ env.ACTION_TOKEN }}
          body: |
            {
              "assignees": ["${{ github.repository_owner }}"]
            }

      - name: Create project card
        if: steps.check_author.outputs.is_owner == 'true'
        uses: peter-evans/create-or-update-project-card@v2
        with:
          column_id: f75ad846
          content_id: ${{ github.event.issue.node_id }}
          content_type: Issue
          mediaType: '{"previews":["inertia"]}'
          token: ${{ env.ACTION_TOKEN }}
